/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_ubc_cs_sandboxer_core_SandboxGuardian */

#ifndef _Included_ca_ubc_cs_sandboxer_core_SandboxGuardian
#define _Included_ca_ubc_cs_sandboxer_core_SandboxGuardian
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_ubc_cs_sandboxer_core_SandboxGuardian
 * Method:    getReferencedSize
 * Signature: ([Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ca_ubc_cs_sandboxer_core_SandboxGuardian_getReferencedSize
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
