/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_ubc_cs_sandboxer_SandboxAppLoader */

#ifndef _Included_ca_ubc_cs_sandboxer_SandboxAppLoader
#define _Included_ca_ubc_cs_sandboxer_SandboxAppLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_ubc_cs_sandboxer_SandboxAppLoader
 * Method:    printMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_ubc_cs_sandboxer_SandboxAppLoader_printMessage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
